spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  #MySQL for user data
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cs-goldteam-server.mysql.database.azure.com:3306/stratego
    username: goldroot@cs-goldteam-server
    password: Cse#)*Gold
  #MongoDB for game data
  data:
    mongodb:
      uri: mongodb://goldroot:Cse#)*Gold@40.85.171.57:27017/test
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

#mongodb: ip: 40.85.171.57 port 27017 user: goldroot pass: Cse#)*Gold

