spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cs-goldteam-server.mysql.database.azure.com:3306/stratego
    username: goldroot@cs-goldteam-server
    password: Cse#)*Gold

